/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestVowelInput {
        "value": string;
    }
}
declare global {
    interface HTMLTestVowelInputElement extends Components.TestVowelInput, HTMLStencilElement {
    }
    var HTMLTestVowelInputElement: {
        prototype: HTMLTestVowelInputElement;
        new (): HTMLTestVowelInputElement;
    };
    interface HTMLElementTagNameMap {
        "test-vowel-input": HTMLTestVowelInputElement;
    }
}
declare namespace LocalJSX {
    interface TestVowelInput {
        "value"?: string;
    }
    interface IntrinsicElements {
        "test-vowel-input": TestVowelInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-vowel-input": LocalJSX.TestVowelInput & JSXBase.HTMLAttributes<HTMLTestVowelInputElement>;
        }
    }
}
